carbon_cloud:
  eureka_address: localhost
server:
  port: 8080
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
spring:
  application:
    name: Carbon-Gateway
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    hostname: carbon-gateway
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${carbon_cloud.eureka_address}:8008/eureka/
