server:
  port: 8080
spring:
  application:
    name: Carbon-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  redis:
    port: 6379
    host: localhost
    database: 3
    password: Maple@feng7
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 500
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8008/eureka/

logging:
  config: classpath:log4j/log4j2-info.yml
#  level:
#    org.springframework.cloud.gateway: debug

# jwt config properties
jwt:
  # secret Key
  secret: JWTSecret,CarbonFace
  # HeaderKey
  tokenHeader: Authorization
  # Token head
  tokenPrefix: Bearer
  # expire time
  expiration: 86400
  # refresh time
  refreshTime: 7
  # no jwt need filter
  antMatchers: /login/**,/carbonface/hello/hello
#mybatis:
#  mapper-locations: classpath*：mybatis/mapper/*Mapper.xml